### ISSUE TITLE
JSON-LD Support

### ISSUE THREAD

**Issue by nicholsn** [blazegraph/database#1]
Is is possible to export a CONSTRUCT query from the Blazegraph NanoSparqlServer GUI or API (e.g., using an HTTP Accept Header) as JSON-LD? If not, is JSON-LD support on the roadmap?

**Comment by beebs-systap** [comment]
The [JSON Sparql Results Format](https://www.w3.org/TR/sparql11-results-json/) is currently configured, JSON-LD could be supported through Sesame 2.7.x by configuring a writer.  Looks like we have an existing [ticket](https://jira.blazegraph.com/browse/BLZG-1017) on this one.

```
curl -X POST http://localhost:9999/blazegraph/sparql --data-urlencode 'query=CONSTRUCT  WHERE { hint:Query hint:analytic "true" . hnt:Query hint:constructDistinctSPO "false" . ?s ?p ?o }' -H 'Accept: application/json'
```

**Comment by nicholsn** [comment]
Thanks for the pointer to your ticketing system. With the growing JSON-LD community, it would be great to have this feature available by default. Looks like it is being addressed in: https://github.com/SYSTAP/bigdata/pull/325
