### ISSUE TITLE
[website] [readme]: SSL Certificates for wiki.blazegraph.com and blog.blazegraph.com expired

### ISSUE THREAD

**Issue by ipa-bak** [blazegraph/database#186]
As per subject,  the two sites
* https://wiki.blazegraph.com/
* https://blog.blazegraph.com/
linked in https://github.com/blazegraph/database/blob/master/README.md use an expired certificate:
![Screenshot from 2020-12-06 15-26-27](https://user-images.githubusercontent.com/22542606/101282817-7c6dd080-37d7-11eb-954d-26277c954739.png)

**Comment by beebs-systap** [comment]
Resolved.
