### ISSUE TITLE
No obvious start-point for compilation and installation

### ISSUE THREAD

**Issue by otheus** [blazegraph/database#20]
Unlike just about every other non-trivial project I've seen, there are no indications of instructions on how to start compiling/building from the given source code.  The instructions should be _in the code base_ and not just on a wiki.  Please at least provide a file in the top-level directory. (There appears to be something in older release data, so maybe the current release file should have this info).

**Comment by otheus** [comment]
Closed without comment? Great. Look , I'm just asking for a few lines of text which describe how to build the project.

**Comment by beebs-systap** [comment]
Here's a link to the text that was added: https://github.com/blazegraph/bigdata/commit/7f9ef175b79dd844f000a3ed487bc48358e22fae.

------
As a quick start, run `mvn install -DskipTests` or the utility script `./scripts/mavenInstall.sh `.
 
 For more detailed maven information see the [wiki](https://wiki.blazegraph.com/wiki/index.php/MavenNotes).
