### ISSUE TITLE
How to run with a different port number?

### ISSUE THREAD

**Issue by otheus** [blazegraph/database#22]
Without using proxies or port-forwarding tools, how can I configure blazegraph to run on a different port number please?

**Comment by mschmidt00** [comment]
Documentation for the NanoSparqlServer can be found on the Wiki:
https://wiki.blazegraph.com/wiki/index.php/NanoSparqlServer#Changing_the_default_port

**Comment by otheus** [comment]
Thanks! What a strange place ("APIs") to document such a thing.
