### ISSUE TITLE
Does Blazegraph support the Graph Store Protocol

### ISSUE THREAD

**Issue by mikebrules** [blazegraph/database#236]
Hello - I'm trying to configure Jena to connect to Blazegraph using the Graph Store protocol

https://www.w3.org/TR/sparql11-http-rdf-update/

..but I can't seem to be able to find out what the Graph Store Endpoint would be for a Blazegraph namespace. Does Blazegraph support this function please?

`String url = "http://192.168.0.7:9999/blazegraph/namespace/products/sparql";`
`RDFConnection conn = RDFConnectionRemote.newBuilder()`
	           ` .destination(url)`
	            `.gspEndpoint("/gsp")`

...doesn't seem to work - I can't find any reference to what the path needs to be.

Thanks in advance,

**Comment by thompsonbry** [comment]
The REST APIs supported by blazegraph are documented here:
https://github.com/blazegraph/database/wiki/REST_API

Blazegraph does not support the graph store protocol.  There was a conflict
with one of the pre-existing REST VERBS for blazegraph.  Delete if I recall
already had been assigned different semantics for Blazegraph.

Thanks,
Bryan

**Comment by mikebrules** [comment]
Many thanks for your help @thompsonbry , much appreciated.
