### ISSUE TITLE
BulkLoader seems to ignore ".xml" extension files

### ISSUE THREAD

**Issue by adimascio** [blazegraph/database#26]
I've deb-installed the 2.1 version of blazegraph and also downloaded the blazegraph.jar bundle file.

I'm trying to bulk load a directory containing a bunch of files with a ".xml" file extension with the following command line:

> java -cp blazegraph.jar com.bigdata.rdf.store.DataLoader fastload.properties mydir

and nothing happens.

If I rename each ".xml" file into ".rdf", files get imported. Is it the expected behavior or did I miss something ?

Thanks for this great project!

Regards,
Adrien

**Comment by beebs-systap** [comment]
Thx!  This is an artifact of the Sesame Rio RDFFormat libraries used to detect the types.  It doesn't register the plain xml type.  Try specifying `-format "RDF/XML"` as a BulkLoader option.
