### ISSUE TITLE
Replicating BlazeGraph DB

### ISSUE THREAD

**Issue by smarek** [blazegraph/database#29]
Hi,

I'm having blazegraph database which is out of my control, and I'd like to set-up clone (duplicate, slave).
Is there any way you could recommend? Only access to the remote DB is through SPARQL HTTP interface.

Thank you!

**Comment by beebs-systap** [comment]
Either [online backup](https://wiki.blazegraph.com/wiki/index.php/REST_API#Online_Backup) or [exporting a namespace](https://wiki.blazegraph.com/wiki/index.php/REST_API#Exporting_a_Namespace) may be an option.
