### ISSUE TITLE
TimeoutException on Raspberry Pi

### ISSUE THREAD

**Issue by eugenesiow** [blazegraph/database#3]
Hi,

I'm trying to start blazegraph on a Raspberry Pi 2 B+ with: `java -server -Xmx800m -jar blazegraph.jar`.

The error I'm getting is:
```
WARN : NanoSparqlServer.java:514: Starting NSS
WARN : ServiceProviderHook.java:171: Running.
Server did not start.
FATAL: NanoSparqlServer.java:535: Server did not start.
ERROR: Banner.java:160: Uncaught exception in thread
java.util.concurrent.TimeoutException
	at com.bigdata.rdf.sail.webapp.NanoSparqlServer.awaitServerStart(NanoSparqlServer.java:525)
	at com.bigdata.rdf.sail.webapp.StandaloneNanoSparqlServer.main(StandaloneNanoSparqlServer.java:150)
```

Is this due to a low resource environment? Is there anyway to set the start server timeout longer?
Cheers!

**Comment by beebs-systap** [comment]
@eugenesiow Add a `-Djetty.start.timeout=60` to your startup.   The value is the timeout in seconds.

`java -Djetty.start.timeout=60 -server -Xmx800m -jar blazegraph.jar`

**Comment by beebs-systap** [comment]
[Wiki](https://wiki.blazegraph.com/wiki/index.php/NanoSparqlServer#Adding_a_Jetty_Startup_Timeout_.28optional.29) is updated with this parameter.

**Comment by eugenesiow** [comment]
Thanks @beebs-systap! Works like a charm!
