### ISSUE TITLE
HTTPRepository strikes on "CONSTRUCT"

### ISSUE THREAD

**Issue by redskate** [blazegraph/database#37]
Hi

I am using HTTPRepository (since one year now) to pass query to remote Blazegraph repositories and get results in java using the SAIL interface in sesame 2.8 (blazegraph jar). All running very well except for the case that the query contains a "CONSTRUCT" statement. In that case, instead of returning results (there are results), the methods

`TupleQuery tupleQuery = con.prepareTupleQuery(QueryLanguage.SPARQL, query);
result = tupleQuery.evaluate();`

throws an exception with message:

`Server responded with an unsupported file format: application/rdf+xml 
org.openrdf.repository.http.HTTPQueryEvaluationException: Server responded with an unsupported file format: application/rdf+xml
	at org.openrdf.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:59)`

The operations SELECT, DELETE, INSERT work as aspected. Just CONSTRUCT does not want.

What should I do in order to let this run ? Is it a bug ? Can I solve this (how) ?

Thanks

**Comment by thompsonbry** [comment]
Your client appears to not be accepting application/rdf+xml.

The Internet media type / MIME type for RDF/XML is application/rdf+xml —
RFC 3023 [RFC3023 <https://www.w3.org/TR/rdf-syntax-grammar/#bib-RFC3023>],
section 8.18.

You can conneg for a different format.  Specify the HTTP Accept header.

But this might be a classpath issue.  Sesame locates the supported parsers
and writers for the RIO package dynamically.  Your client might not be
finding them.  Look at the RIO package.

If you are using the Blazegraph client, try invoking
ServiceProviderHook.forceLoad().  This is called from our
RemoteRepositoryManager constructor.

Thanks,
Bryan

**Comment by redskate** [comment]
The Client is built with blazegraphs HTTPRepository class, which is a wrap method to talk via http with a blazegraph server.
That client (HTTPRepository) exchanges in some format (until today I did not bother in which format this class and the server are exchanging)-
In the case of well functioning queries containing e.g. SELECT this class HTTPRepository must ergo be exchanging in another format ? Without having reverse engineered it, it seems to me a bit strange.
Thank you for the hint with ServiceProviderHook.forceLoad(). I will learn what for it was done and how to use it.

Meanwhile I managed to reformulate my CONSTRUCT query using SELECT and the world seems to be again “running”.

Thank you

**Comment by thompsonbry** [comment]
The root cause is likely to be a change in the order in which the JARs are
being loaded causing initialization to not find the RIO parser for
application/rdf+xml.

Bryan

**Comment by redskate** [comment]
Good guess!!!!
Thank you Brian

Regards

**Comment by redskate** [comment]
But: The RIO classes are all packaged inside the blazegraph jar.
So theoretically I would have to analyse and reorder them and rebuild the jar, right?

Do you think this could be a hint for SYSTAP to do it (in some future release) ?

Regards

**Comment by igor-kim** [comment]
While creating blazegraph one-jar artifact, maven-shade plugin is already used to repack dependencies and properly merge parsers and writers configurations.

@redskate , could you provide a code snippet which establishes connection and executes query in question? 

There is TupleQuery mentioned in the original message, which does not support application/rdf+xml format used for a CONSTRUCT query response. That might case an error. GraphQuery should be used for CONSTRUCT queries.

**Comment by redskate** [comment]
Hi Igor

here the snipped:

			TupleQuery tupleQuery = con.prepareTupleQuery(QueryLanguage.SPARQL, query);
			tupleQuery.setIncludeInferred(false /* includeInferred */);
			result = tupleQuery.evaluate();

In query was a “construct” query passed.

So in case of CONSTRUCT it should be 
			GraphQuery graphQuery = con.prepareGraphQuery(QueryLanguage.SPARQL, query);
			graphQuery.setIncludeInferred(false /* includeInferred */);
			result = graphQuery.evaluate();
right?

(thank you for this valuable hint!!)
Regards

**Comment by igor-kim** [comment]
@redskate , yes, that's correct, you would need to use GraphQuery for CONSTRUCT and TupleQuery for SELECT. Does that resolves your initial question?

**Comment by redskate** [comment]
@igor-kim yes, it does definitely :) Thank you Igor
