### ISSUE TITLE
use sparql will show:Another process that has locked a file part of the process can not be accessed

### ISSUE THREAD

**Issue by kangpengjie** [blazegraph/database#39]
The code is below:
public static void main(String[] args) throws Exception {		
		final BigdataGraph graph = new BigdataGraphClient("http://localhost:9999/blazegraph/sparql");
		for(int i = 0; i< 50; i++) {
				Vertex v = graph.addVertex(null);
				v.setProperty("name", "vertex" + i);				
		}
ICloseableIterator<BigdataBindingSet> a = graph.select("select (COUNT(?s) AS ?count) where {?s ?p ?o}");
a.close();
graph.shutdown();
}
this code The first few times run is good,then will throw:Another process that has locked a file part of the process can not be accessed。

**Comment by thompsonbry** [comment]
Please provide a thread dump from java.  This should show where the
deadlock is occurring.  Also, please provide the blazegraph version number.

Thanks,
Bryan

**Comment by kangpengjie** [comment]
I run the BlazeGraph Server Version is 2.1.1。
[error log.txt](https://github.com/blazegraph/database/files/644978/error.log.txt)

**Comment by kangpengjie** [comment]
I run the server on window7。Today I Run the server on centos,until now not found error。

**Comment by thompsonbry** [comment]
This is likely to be a Windows specific issue.  The asynchronous IO support needs to be disabled on Windows.  I believe that this is automatically done in the current release.

Thanks,
Bryan

@beebs-systap

**Comment by beebs-systap** [comment]
Yes, this is likely [BLZG-1911](https://jira.blazegraph.com/browse/BLZG-1911), which was resolved in 2.1.2.


You can also set _readBlobsAsync_ to false in your your journal properties.
```
com.bigdata.rwstore.RWStore.readBlobsAsync=false
```
