### ISSUE TITLE
DELETE DATA on statements with typed values

### ISSUE THREAD

**Issue by redskate** [blazegraph/database#57]
Hi

I am using bigdata 2.1.4

When in a repository there is a statement like

<http://someurl.ch> <http://someprop.ch> "hello"^^<https://www.w3.org/TR/xmlschema11-2/#string>

the corrisponding DELETEDATA statement

DELETE DATA {
<http://someurl.ch> <http://someprop.ch> "hello"^^<https://www.w3.org/TR/xmlschema11-2/#string>
}

does not find it, while the statement

DELETE DATA {
<http://someurl.ch> <http://someprop.ch> "hello"
}

finds it. 

Why is this so??? Is it my mistake?

**Comment by thompsonbry** [comment]
I believe the rdf 1.1 support might be in the 2.x RC branch. Those are not
the same data under RDF 1.0.

**Comment by redskate** [comment]
ist this the solution to my question?
what should I do ?

**Comment by thompsonbry** [comment]
Use the explicit xsd:string datatype.
