### ISSUE TITLE
Not using W3C OWL Time ontology time:number correctly?

### ISSUE THREAD

**Issue by fils** [blazegraph/database#59]
A colleague and I are seeing incorrect results from Blazegraph when using the W3C OWL Time ontology time:Number RDFS Class (ref: https://www.w3.org/TR/owl-time/#time:Number )

Loading the graph:  https://github.com/dr-shorthair/GeologicTimeScale/blob/master/ISC/isc2016-12-time.ttl 

and using the SPARQL queries at: https://github.com/dr-shorthair/GeologicTimeScale/issues/1

results in invalid returns for all three using 2.1.1 and 2.1.5 SNAPSHOT.   With the query for 66 million years (this a Geologic Time graph used in deep time geological science work) no results return, for the others a subset of valid results returns.  We should get results with  isc:Phanerozoic as a single result for 66.    For 65 and 67 million years Blazegraph returns 3 results, but there should have been 5 in each case.

Simon Cox of CSIRO Astralia notes the results expected and a potential issue around reading time:Numeric in his comment at https://github.com/dr-shorthair/GeologicTimeScale/issues/1#issuecomment-292781921 

This query works in TopBraid, but not in Blazegraph as he notes.

**Comment by thompsonbry** [comment]
Blazegraph does not support OWL directly.  There is an integration of the
elk reasoner with OWL which is developed and maintained by Jim Balhoff
(Cc).  Without OWL based reasoning, the queries may be incomplete with
respect to the ontology.

Thanks,
Bryan
