### ISSUE TITLE
presigned s3 url of *.gz will not get load

### ISSUE THREAD

**Issue by tle** [blazegraph/database#6]
For instance , consider this url 
`https://some-bucket.s3.amazonaws.com/triples-file.nt.gz?x-amz-security-token=XXX&AWSAccessKeyId=XXXX&Expires=1463756979&Signature=XXXX`

The following sparql update  `load <https://some-bucket.s3.amazonaws.com/triples-file.nt.gz?x-amz-security-token=XXX&AWSAccessKeyId=XXXX&Expires=1463756979&Signature=XXXX>` will load 0 triples . 

I tracked this down to https://github.com/blazegraph/database/blob/98ebb1fad31aa38859ab8202385b89eeb35f22a0/bigdata-core/bigdata-rdf/src/java/com/bigdata/rdf/sparql/ast/eval/AST2BOpUpdate.java#L1596   .   Note how the code is is use ```n.endsWith``` predicate to decide whether to use gzipInputStream . In the case of this url , n is ```triples-file.nt.gz?x-amz-security-token=XXX&AWSAccessKeyId=XXXX&Expires=1463756979&Signature=XXXX``` . 

I think this is a bug

**Comment by beebs-systap** [comment]
@tle Yes, agreed.  We should be using the content-type from the HTTP header.    Do you mind filing a ticket at (JIRA)[https://jira.blazegraph.com/] and we'll get it in the backlog.

**Comment by tle** [comment]
https://jira.blazegraph.com/browse/BLZG-1929

**Comment by beebs-systap** [comment]
Resolved in 2.1.1 release.
