### ISSUE TITLE
Dead Links on wiki.blazegraph.com

### ISSUE THREAD

**Issue by kevinkle** [blazegraph/database#60]
Specifically, looking for info. on:
* https://www.bigdata.com/docs/api/com/bigdata/rdf/axioms/Axioms.html
* https://www.bigdata.com/docs/api/com/bigdata/rdf/rules/FastClosure.html
* https://www.bigdata.com/docs/api/com/bigdata/rdf/rules/FullClosure.html

Any alt. links?

**Comment by thompsonbry** [comment]
https://blazegraph.github.io/database/apidocs/index.html

We are no longer using the bigdata.com domain.

Thanks,
Bryan

**Comment by KMax** [comment]
The https://wiki.blazegraph.com/wiki/index.php/FullTextSearch page has links with `bigdata.com` domain.

**Comment by beebs-systap** [comment]
Thanks. I've updated the wiki page to correct the links.

**Comment by beebs-systap** [comment]
In general, the link should be prefixed as `https://blazegraph.github.io/database/apidocs/`, i.e.

https://blazegraph.github.io/database/apidocs/com/bigdata/rdf/axioms/Axioms.html
