### ISSUE TITLE
question inputstream

### ISSUE THREAD

**Issue by publicocean0** [blazegraph/database#61]
Hi,can i save inputstream in blazegraph?

**Comment by thompsonbry** [comment]
We do not support writing input streams to the RDF database.  There are low
level APIs for writing streams to the backing store.  E.g., Look at the
RWStore and the PSOutputStream API.

Thanks,
Bryan

**Comment by publicocean0** [comment]
I want make compliments to you for this project . I was realizing a database including also graph , but when yesterday I found this project I understood there are people more capable than me. I hope just you are a team , I could tell me a reason because of my simplier db :) 

Inviato da iPad
