### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by alu-ixxus** [blazegraph/database#68]
Hello,

I wonder if anyone from blazegraph to point me whom to contact regarding commercial license? I can't find any contact details from https://www.blazegraph.com/.

Thanks!

**Comment by beebs-systap** [comment]
@alu-ixxus Feel free to contact me at `beebs` _at_ `blazegraph.com` and we can discuss options.

**Comment by alu-ixxus** [comment]
@beebs-systap I've emailed you a couple of days ago and just wondering if you have received it. Would be great if you could send me any information regarding commercial license. Thanks!

**Comment by akuckartz** [comment]
Why is this issue still open?
