### ISSUE TITLE
ERROR: RDF store reports the last update time is before the minimum safe poll 

### ISSUE THREAD

**Issue by loretoparisi** [blazegraph/database#96]
We get this error while updating

```
10:48:37.828 [main] ERROR org.wikidata.query.rdf.tool.Update - Error during initialization.
java.lang.IllegalStateException: RDF store reports the last update time is before the minimum safe poll time.  You will have to reload from scratch or you might have missing data.
    at org.wikidata.query.rdf.tool.Update.getStartTime(Update.java:204)
    at org.wikidata.query.rdf.tool.Update.buildRecentChangePollerChangeSource(Update.java:182)
    at org.wikidata.query.rdf.tool.Update.buildChangeSource(Update.java:171)
    at org.wikidata.query.rdf.tool.Update.main(Update.java:78)
```

We have downloaded the latest wikipedia dump (02.07) and started the update against a previous dump.

**Comment by loretoparisi** [comment]
Does this relies to this issue: https://phabricator.wikimedia.org/T182394

where it's stated `Looks like you're trying to run Updater on empty database without any incoming data. Probably not the use case it was intended for, but not sure what is supposed to happen in this case... Generally Updater would not attempt to catch up if it's more than 30 days behind, since for most active DBs that would be pointless - it would take many days to catch up. But this probably can be changed for testing purposes...`

**Comment by thompsonbry** [comment]
This is wikidata code.  Adding Stas.

Bryan

**Comment by smalyshev** [comment]
This looks like the case where initial state of the database is more than 30 days behind current date. In this case, you may want to do one of:
1. Load a recent dump
2. Use -s DATE --init option with Updater to initialize start date
3. Use -DwikibaseMaxDaysBack=DAYS when running Updater (I would still recommend using -s DATE to have some starting point if you are starting with empty database) to start more than 30 days back. If you're using Wikidata as data source, though, I'd really recommend recent dump instead, catching up from 30+ days back is going to take a long time. If it's your own smaller WIkibase, it may be fine. 

If this still does not work, please ping me and send me the full log from the start, with -v option, so I could see what is going on there.

**Comment by loretoparisi** [comment]
@smalyshev thank you for your support, it is working with this approach! cc @albertopinardi

**Comment by tinycatalyzer** [comment]
> This looks like the case where initial state of the database is more than 30 days behind current date. In this case, you may want to do one of:
> 
> 1. Load a recent dump
> 2. Use -s DATE --init option with Updater to initialize start date
> 3. Use -DwikibaseMaxDaysBack=DAYS when running Updater (I would still recommend using -s DATE to have some starting point if you are starting with empty database) to start more than 30 days back. If you're using Wikidata as data source, though, I'd really recommend recent dump instead, catching up from 30+ days back is going to take a long time. If it's your own smaller WIkibase, it may be fine.
> 
> If this still does not work, please ping me and send me the full log from the start, with -v option, so I could see what is going on there.

@smalyshev , hi I'm having the same problem now when running Updater within the wikibase docker-compose.yml file. This is a brand new installation, so I'm not sure how the database can be over 30 days old. Would you please assist?

**Comment by DavidFichtmueller** [comment]
@tinycatalyzer : I had the same issue and google brought me here, so even if this might not help you anymore, maybe this will help others who get here with the same error message.

**The problem** is (as I understand it), that the image on docker hub of the wdqs (which has the blazegraph instance in it) was build too long ago. 
**The solution** is to rebuild the image locally. Go in the file docker-compose.yml and after the lines
```
  wdqs:
    image: wikibase/wdqs:0.3.40
```
add 
```
    build:
      context: ./wdqs/0.3.40
      dockerfile: Dockerfile
```
and then run
`docker-compose up -d --build`

This helped me and I hope it helped others as well. Sorry for hijacking this issue.
