### ISSUE TITLE
Improve slow queries when using  FILTER REGEX

### ISSUE THREAD

**Issue by loretoparisi** [blazegraph/database#97]
We are facing slow queries when dealing with statements with a `REGEX` filter. We do this to use as a `contain` pattern matching. Is there an alternative and more efficient way to achieve that?

```sparql
SELECT DISTINCT ?artist ?artistLabel ?birth_nameLabel  ?date ?website ?instagramID ?facebookID ?twitterID ?musicBrainzArtistID WHERE {
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }

    { ?artist wdt:P31 wd:Q215380. }
    UNION
    { ?artist wdt:P31 wd:Q2088357. }
    UNION
    { ?artist wdt:P31 wd:Q5741069. }
    UNION
    { ?artist wdt:P31 wd:Q641066. }
     UNION
    { ?artist wdt:P1902 ?_spotifyArtistID_. }
    UNION
    { ?artist wdt:P2850 ?_itunesArtistID_. }
    UNION
    { ?artist wdt:P434 ?musicBrainzArtistID. } 

      FILTER(REGEX(?artistLabel, "^Fall Out Boy$", "i"))
      ?artist rdfs:label ?artistLabel.

      OPTIONAL { ?artist wdt:P571 ?date. }
      OPTIONAL { ?artist wdt:P1477 ?birth_nameLabel. }
      OPTIONAL { ?artist wdt:P856 ?website. }
      OPTIONAL { ?artist wdt:P2003 ?instagramID. }
      OPTIONAL { ?artist wdt:P2013 ?facebookID. }
      OPTIONAL { ?artist wdt:P2002 ?twitterID. }


  }
  LIMIT 10
```

I have asked as a question on SF as well [here](https://stackoverflow.com/questions/51060591/slow-blazegraph-sparql-queries-with-union-and-filter), and got some interesting suggestion like replacing `UNION` with `VALUES` like

```sparql
VALUES ?artistType {wd:Q215380 wd:Q2088357wd:Q5741069 wd:Q641066} ?artist wdt:P31 ?artistType .
```

**Comment by thompsonbry** [comment]
The REGEX is not backed by an index. It is simply a filter applied to
solutions identified by earlier parts of the query.  If the regex itself is
the issue, i suggest that you make sure it is evaluated late in the query
(look at the explain of the query). It should be after you have evaluated
any non-optional constraints.

VALUES can be used to inject specific solutions (bindings on some
variables) into the query. But this has no direct interaction with REGEX.
It is a separate question how to optimize the query without the REGEX.  Of
course, that might be a good place for you to start,

Bryan

**Comment by loretoparisi** [comment]
@thompsonbry thanks a lot for this suggestion, I will take a look how to replace REGEX with something different.
